name: Deploy Thesis App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies and EB CLI
      - name: Install dependencies and EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install six==1.16.0 
          pip install awsebcli
          pip install -r requirements.txt

      # Step 4: Configure AWS credentials using GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Step 5: Initialize the EB CLI configuration
      - name: Initialize EB CLI
        run: |
          eb init Thesis -p python-3.12 --region us-west-2

      # Step 6: Deploy the latest version to your EB environment
      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy thesis-env

