name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Grab your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Python deps
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Install docker-compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # 4. (Optional) Test your Python code
      # - name: Run tests
      #   run: pytest

      # 5. Build your containers
      - name: Build Docker Compose services
        run: docker-compose build

