name: Deploy Thesis App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) set up Python, EB CLI & Docker Compose
      - name: Set up Python & tools
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies, EB CLI & Docker Compose
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install awsebcli
          sudo apt-get update && sudo apt-get install -y docker-compose

      # 3) make sure your containers build cleanly
      - name: Build Docker Compose services
        run: docker-compose build

      # 4) load AWS creds into env
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      # 5) initialize EB (no --bucket flag!)
      - name: Initialize Elastic Beanstalk
        run: |
          eb init Thesis \
            --region us-east-1 \
            --platform docker \
            --verbose

      # 6) point to your existing environment (must already exist)
      - name: Select EB environment
        run: eb use thesis-env

      # 7) finally deploy
      - name: Deploy to Elastic Beanstalk
        run: eb deploy --staged

