name: Deploy Thesis App to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) get your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) install Python & EB CLI & docker-compose
      - name: Set up Python & Tools
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies, EB CLI & Docker Compose
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install awsebcli
          sudo apt-get update && sudo apt-get install -y docker-compose

      # 3) build your service to catch Dockerfile/compose errors early
      - name: Build Docker Compose services
        run: docker-compose build

      # 4) configure AWS creds in the correct region
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      # 5) init EB for your app & platform
      - name: Initialize Elastic Beanstalk
        run: |
          eb init Thesis \
            --region us-east-1 \
            --platform docker \
            --bucket your‑existing‑bucket-name

      # 6) tell EB which environment to target
      - name: Select EB environment
        run: eb use thesis-env

      # 7) deploy
      - name: Deploy to Elastic Beanstalk
        run: eb deploy

